# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bili_tui = {
    pname = "bili_tui";
    version = "44412397dde7de3190466af3d4cff1c62396a998";
    src = fetchFromGitHub {
      owner = "yaocccc";
      repo = "bilibili_live_tui";
      rev = "44412397dde7de3190466af3d4cff1c62396a998";
      fetchSubmodules = false;
      sha256 = "sha256-th66czpHiLdZRqXVGpxVLh2lrvrjXErniJzuwVNZsP0=";
    };
    date = "2023-04-24";
  };
  bird-babel-rtt = {
    pname = "bird-babel-rtt";
    version = "bcbd53c4966cb59a50aa9d004250e08d10038250";
    src = fetchFromGitHub {
      owner = "NickCao";
      repo = "bird";
      rev = "bcbd53c4966cb59a50aa9d004250e08d10038250";
      fetchSubmodules = false;
      sha256 = "sha256-9DxTnftcJ52JTvTWW+V37VQR1aXL0Nt0sHXVcOicrbU=";
    };
    date = "2023-10-07";
  };
  fcitx5-pinyin-zhwiki = {
    pname = "fcitx5-pinyin-zhwiki";
    version = "20231205";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-20231205.dict";
      sha256 = "sha256-crMmSqQ7QgmjgEG8QpvBgQYfvttCUsKYo8gHZGXIZmc=";
    };
  };
  sway-git = {
    pname = "sway-git";
    version = "7e69a7076fc8a4eb788e0229b1c99dd0b7b04bb7";
    src = fetchFromGitHub {
      owner = "swaywm";
      repo = "sway";
      rev = "7e69a7076fc8a4eb788e0229b1c99dd0b7b04bb7";
      fetchSubmodules = false;
      sha256 = "sha256-7kO+KaRbzwKkZBLmkODxjgEHqkx2vw+fraTMZ23s+iI=";
    };
    date = "2024-01-04";
  };
  wlroots-git = {
    pname = "wlroots-git";
    version = "48721bca656556606275a5e776066a2f00822e92";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wlroots/wlroots.git";
      rev = "48721bca656556606275a5e776066a2f00822e92";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-PUx4RZiLbWineoAvZk7kuUBXRFI15vfxLna49LUR8+s=";
    };
    date = "2024-01-07";
  };
  xwayland-xprop = {
    pname = "xwayland-xprop";
    version = "23.2.3";
    src = fetchurl {
      url = "https://xorg.freedesktop.org/archive/individual/xserver/xwayland-23.2.3.tar.xz";
      sha256 = "sha256-652apyMsR0EsiDXsFal8V18DVjcmx4d1T/DAGb0H4wI=";
    };
  };
}
