# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bili_tui = {
    pname = "bili_tui";
    version = "44412397dde7de3190466af3d4cff1c62396a998";
    src = fetchFromGitHub {
      owner = "yaocccc";
      repo = "bilibili_live_tui";
      rev = "44412397dde7de3190466af3d4cff1c62396a998";
      fetchSubmodules = false;
      sha256 = "sha256-th66czpHiLdZRqXVGpxVLh2lrvrjXErniJzuwVNZsP0=";
    };
    date = "2023-04-24";
  };
  bird-babel-rtt = {
    pname = "bird-babel-rtt";
    version = "bcbd53c4966cb59a50aa9d004250e08d10038250";
    src = fetchFromGitHub {
      owner = "NickCao";
      repo = "bird";
      rev = "bcbd53c4966cb59a50aa9d004250e08d10038250";
      fetchSubmodules = false;
      sha256 = "sha256-9DxTnftcJ52JTvTWW+V37VQR1aXL0Nt0sHXVcOicrbU=";
    };
    date = "2023-10-07";
  };
  fcitx5-pinyin-zhwiki = {
    pname = "fcitx5-pinyin-zhwiki";
    version = "20231016";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-20231016.dict";
      sha256 = "sha256-aQAAg+ArqwI5/fbhY80oAkvpRonU6FUsfYuWp3Z2WCM=";
    };
  };
  sway-git = {
    pname = "sway-git";
    version = "5c99b98805e8171d590d466b2eb21402aaf8de6b";
    src = fetchFromGitHub {
      owner = "swaywm";
      repo = "sway";
      rev = "5c99b98805e8171d590d466b2eb21402aaf8de6b";
      fetchSubmodules = false;
      sha256 = "sha256-Ow/tFFtrwcjBCBgeoUwCGObT/z7FvpBveKoh3UssSAk=";
    };
    date = "2023-11-16";
  };
  wlroots-git = {
    pname = "wlroots-git";
    version = "c9c9dd6a5b866055a6a39fd78e55f6d5797fec28";
    src = fetchgit {
      url = "https://gitlab.freedesktop.org/wlroots/wlroots.git";
      rev = "c9c9dd6a5b866055a6a39fd78e55f6d5797fec28";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-dUZrwAJnJGa2q/3MPcO6f1xweaT6+Z8/9vjsaPomUxE=";
    };
    date = "2023-11-17";
  };
  xwayland-xprop = {
    pname = "xwayland-xprop";
    version = "23.2.2";
    src = fetchurl {
      url = "https://xorg.freedesktop.org/archive/individual/xserver/xwayland-23.2.2.tar.xz";
      sha256 = "sha256-n3wJONKkHpQf+gT5nDXl2yvNPuwDSv6NNdXIEKIusKg=";
    };
  };
}
