# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bird-babel-rtt = {
    pname = "bird-babel-rtt";
    version = "bcbd53c4966cb59a50aa9d004250e08d10038250";
    src = fetchFromGitHub {
      owner = "NickCao";
      repo = "bird";
      rev = "bcbd53c4966cb59a50aa9d004250e08d10038250";
      fetchSubmodules = false;
      sha256 = "sha256-9DxTnftcJ52JTvTWW+V37VQR1aXL0Nt0sHXVcOicrbU=";
    };
    date = "2023-10-07";
  };
  fcitx5-pinyin-zhwiki = {
    pname = "fcitx5-pinyin-zhwiki";
    version = "20231016";
    src = fetchurl {
      url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-20231016.dict";
      sha256 = "sha256-aQAAg+ArqwI5/fbhY80oAkvpRonU6FUsfYuWp3Z2WCM=";
    };
  };
  sway = {
    pname = "sway";
    version = "020a572ed615b8fe272c7566a27ee0abe73a58d7";
    src = fetchFromGitHub {
      owner = "swaywm";
      repo = "sway";
      rev = "020a572ed615b8fe272c7566a27ee0abe73a58d7";
      fetchSubmodules = false;
      sha256 = "sha256-Vu4DHIOqNmqVeAuqRLOAW5LXoTqzuglUjw4Pg7lAAUE=";
    };
    date = "2023-11-03";
  };
}
